Step1 - 문자열 덧셈 계산기
zuniors/java-lotto pull request #1
Opened 2020-05-19 02:24 UTC by gmlwjd9405

## 기능 요구사항 목록 
#### StringCalculator
- [x] 빈 문자열 또는 null 값을 입력할 경우 0을 반환해야 한다.(예 : “” => 0, null => 0)
- [x] 음수를 전달할 경우 RuntimeException 예외가 발생해야 한다. (예 : “-1,2,3”)
- [x] 숫자 이외의 값을 전달할 경우 RuntimeException 예외가 발생해야 한다. (예: "a,1")
- [x] 숫자 하나를 문자열로 입력할 경우 해당 숫자를 반환한다.(예 : “1”)
- [x] 숫자 두개를 컴마(,) 구분자로 입력할 경우 두 숫자의 합을 반환한다.(예 : “1,2”)
- [x] 구분자를 컴마(,) 이외에 콜론(:)을 사용할 수 있다. (예 : “1,2:3” => 6)
- [x] “//”와 “\n” 문자 사이에 커스텀 구분자를 지정할 수 있다. (예 : “//;\n1;2;3” => 6)
    - ; : & @ # %   = - ! ] }
- [x] “//”와 “\n” 문자 사이에 정규표현식 meta char 를 커스텀 구분자로 지정할 수 있다.
    - . | ^ $ * + ? ( [ { )
- [x] 커스텀 구분자 형식의 문자열 중 숫자값을 빈 문자열로 입력한 경우 0을 반환한다.
    - (예 : “//:\n” => 0) (차이 : “//:\n2:3::” => 6)
    
#### Number
- [x] 음수값 문자의 경우 예외가 발생한다.
- [x] 숫자 이외의 값을 전달하는 경우 예외가 발생한다.
- [x] 빈 문자열 또는 null 값을 입력할 경우 예외가 발생한다.
- [x] 0 이상의 양의 값 문자가 들어오면 Number 객체를 생성할 수 있다.
- [x] 인수로 받은 값과 합한 값의 Number 객체를 반환한다.
- [x] 자신의 숫자값을 반환할 수 있다.

#### Splitter
- 공통
    - 빈 문자열을 입력하면 빈 String 배열을 반환한다.
    - null 을 입력하면 NullPointerException 예외 발생
    - [x] 문자열이 커스텀 구분자 형식이 아니면 기본 구분자로 split 한다.
    - [x] 문자열이 커스텀 구분자 형식이면 커스텀 구분자로 split 한다.
- 기본 구분자
    - [x] 빈 문자열을 입력하면 빈 String 배열을 반환한다.
    - [x] null 을 입력하면 NullPointerException 예외 발생
    - [x] 콜론(:) 또는 콤마(,)를 구분자로 분리한 String 배열을 반환한다.
    - [x] 기본 구분자는 기본으로 문자열 계산기에 지원되는 구분자이므로 항상 지원 가능하다.
- 커스텀 구분자 
    - [x] 빈 문자열을 입력하면 빈 String 배열을 반환한다.
    - [x] null 을 입력하면 NullPointerException 예외 발생
    - [x] 매칭되지 않는 정규 표현식 문자열 들어오면 예외 발생 
    - [x] 커스텀 구분자로 분리한 숫자 String 배열을 반환한다.
    - [x] 커스텀 구분자는 문자열이 정규표현식 패턴에 매칭이 되어야 지원 가능하다.
        - (private) 커스텀 구분자 형식의 문자열인지 확인할 수 있다.
- Splitter 관리자
    - [x] 우선 커스텀 구분자에 매칭되는 문자열이면 커스텀 구분자를 Splitter 로 반환한다.
    - [x] 커스텀 구분자가 지원되지 않는 문자열이면 기본 구분자를 Splitter 로 반환한다.

#### StringUtil
- [x] 문자열이 빈 문자열이거나 null 인 경우 return true
- [x] 문자가 Integer 로 변환할 수 없는 값인 경우 NumberFormatException 예외 발생 

#### Exception
- [x] RuntimeException 대신 명확한 exception 을 사용한다.
- [x] 구체적인 Error Message 를 지정한다.

2020-05-19 03:45 UTC, nokchax requested changes
수고하셨숨다 👏👏👏

TDD를 적용하기 위한 커밋수가 인상적이네요... 😲😲
구조는 잘 짜셨어요, SplitterManager에서 매칭되는 Splitter를 반환하는게 인상적이었습니다 💯 👍👍👍     
테스트 코드는 꼼꼼하게 짜신것 같고, 자잘한 코멘트 몇개 달아놨습니다.

2020-05-19 03:45 UTC, nokchax commented on src/main/java/StringCalculator.java
> +                .reduce(Number.ZERO, Number::plus)
호옹 ruduce :+1:

2020-05-19 03:45 UTC, nokchax commented on src/main/java/number/Number.java
> +    private Number(final String number) throws NumberFormatException {
`RuntimeException` 을 굳이 써준 이유가 있나요?
명시하기 위해서?

2020-05-19 03:45 UTC, nokchax commented on src/main/java/number/Number.java
> +    }
```suggestion
    public static Number of(final String number) {
        int parsedInt = StringUtil.toInt(number);
        
        return new Number(parsedInt);
    }
```

이런식으로 하면 중복을 없앨수 있을거 같은데 어떤가요?

2020-05-19 03:45 UTC, nokchax commented on src/main/java/StringCalculator.java
> +        return false;
```suggestion
        return numbers == EMPTY_ARRAY;
```
이런 방식은 어떤가요?
여기는 처음 봤을때 어떤건지 확 느낌이 안오더라구요

2020-05-19 03:45 UTC, nokchax commented on src/main/java/splitter/SplitterManager.java
> +    private List<Splitter> splitters;
wow 😲 Splitter 추가가 편하겠네요 
조금 더 나아가서 동일한 Splitter 가 들어가지 않도록 Set을 사용하는 방식도 괜찮을거 같아요

2020-05-19 03:45 UTC, nokchax commented on src/main/java/splitter/SplitterManager.java
> +    }
현재는 두개의 Splitter 만 사용하기 떄문에,
매번 생성하는 것 보단
```java
public static final SplitterManager SPLITTER_MANAGER = new SplitterManger();
```
혹은
```java
private static final List<Splitter> SPLITTERS = Arrays.asList(new CustomSplitter(), new CommaAndColonSplitter());
```
를 활용하는건 어떨까요 ? ❓

2020-05-19 03:45 UTC, nokchax commented on src/main/java/splitter/SplitterManager.java
> +                .orElse(new CommaAndColonSplitter());
splitter에 이미 CommaAndColonSplitter가 있는데 orElse로 동일한 Splitter를 넘겨 주는 것 보다는
exception을 발생시키는게 어떨까요?

2020-05-19 03:45 UTC, nokchax commented on src/main/java/splitter/CustomSplitter.java
> +    private final Pattern CUSTOM_PATTERN = Pattern.compile(CUSTOM_DELIMITER_REGEX);
정적 변수가 아니라, 변수명을 바꿔줘야 할거 같아요

2020-05-19 03:45 UTC, nokchax commented on src/main/java/splitter/CustomSplitter.java
> +        return CUSTOM_PATTERN.matcher(value).find();
find()보다는 matches() 가 더 어울릴 거 같아요, 처음부터 끝까지 패턴 형식에 맞아야하는 거니까요

[참고](https://stackoverflow.com/a/4450166) https://stackoverflow.com/a/4450166

2020-05-19 03:45 UTC, nokchax commented on src/main/java/splitter/CustomSplitter.java
> +        throw new IllegalArgumentException();
여기서는 문맥을 나누는 용도로 개행을 적절하게 사용해봐요

2020-05-19 03:45 UTC, nokchax commented on src/main/java/splitter/CustomSplitter.java
> +        }
throw문이 if밖에 있으니까 뭔가 이상한거 같네요, 아래 방식은 어떨까요
```java
if (!matcher.find()) {
    throw ...
}
```
전에도 말씀드렸지만 if문 안쪽이 간결한 방식이 좋을거 같습니다. find()가 true일때 실행해야할 명령이 많아지만 if문 안쪽이 간결한 편이 나을거 같아요

2020-05-19 03:45 UTC, nokchax commented on src/main/java/splitter/Splitter.java
> +    String[] EMPTY_ARRAY = new String[0];
```suggestion
    String[] EMPTY_ARRAY = new String[] {};
```
매직넘버 보다는 이게 나을거 같네요

2020-05-19 03:45 UTC, nokchax commented on src/main/java/splitter/SplitterManager.java
> +                .orElse(new CommaAndColonSplitter());
어차피 CommaAndColonSplitter에서 항상 true를 반환하기도 하구요

2020-05-19 03:45 UTC, nokchax commented on src/main/java/splitter/SplitterManager.java
> +    private List<Splitter> splitters;
입력 순서를 보장하는 set에는 LinkedHashSet 이 있슴돠 😃

2020-05-19 03:49 UTC, nokchax commented on src/main/java/StringCalculator.java
> +        return false;
아 이게 아니구나.......??ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2020-05-19 03:50 UTC, gmlwjd9405 commented on src/main/java/splitter/CustomSplitter.java
> +    private final Pattern CUSTOM_PATTERN = Pattern.compile(CUSTOM_DELIMITER_REGEX);
아, 그렇네요!! ㅎㅎ

2020-05-19 04:17 UTC, gmlwjd9405 commented on src/main/java/number/Number.java
> +    private Number(final String number) throws NumberFormatException {
맞습니다.. `StringUtil.toInt()`의 `Integer.parseInt(number)` 에서 이미 number 가 null 이거나 빈 문자열일 때 NumberFormatException 을 던지는데
제가 위에서 validate 를 하나 더 만들게 되더라구여... 그래서 명시적으로 적어두긴 했는데 빼는 게 더 나을 거 같네요!ㅎㅎ

2020-05-19 04:26 UTC, nokchax commented on src/main/java/StringCalculator.java
> +        return false;
좀 더 보고 다시 달게요!

2020-05-19 04:35 UTC, gmlwjd9405 commented on src/main/java/StringCalculator.java
> +        return false;
저도 이거 때문에 엄청 고민을 했는데... validate 를 한 이유가

- [x] 커스텀 구분자 형식의 문자열 중 숫자값을 빈 문자열로 입력한 경우 0을 반환한다. (예 : “//:\n” => 0) 

이 요구사항 때문인데, 이 경우가 EMPTY_ARRAY를 의미하는 게 아니라 String 배열에서 빈 문자열이 하나가 있는 상황입니다 😭

2020-05-19 04:48 UTC, gmlwjd9405 commented on src/main/java/splitter/SplitterManager.java
> +    private List<Splitter> splitters;
참고: [convert-array-to-linkedhashset-in-java-example](https://www.javacodeexamples.com/convert-array-to-linkedhashset-in-java-example/3051)

2020-05-19 08:08 UTC, gmlwjd9405 commented on src/main/java/splitter/CustomSplitter.java
> +    private final Pattern CUSTOM_PATTERN = Pattern.compile(CUSTOM_DELIMITER_REGEX);
```
private static final List<String> REGEX_META_CHAR = Collections.unmodifiableList(
            Arrays.asList(".", "|", "^", "$", "*", "+", "?", "(", "[", "{", ")")
    );
```
```
private static final List<String> REGEX_META_CHAR = 
            Arrays.asList(".", "|", "^", "$", "*", "+", "?", "(", "[", "{", ")");
```

- pattern이 리소스를 많이 잡아먹기 때문에 내부의 패턴이 변하지 않는 이상 `private static final  Pattern` 로 사용하는 게 좋다는 것도 알게 됐네요! 😄

2020-05-19 08:11 UTC, gmlwjd9405 commented on src/main/java/StringCalculator.java
> +        return false;
```
private static final String EMPTY_OPERAND_REGEX = "//(.)\n";
private static final Pattern emptyOperandPattern = Pattern.compile(EMPTY_OPERAND_REGEX);

@Override
public String[] split(final String value) {
    if (value.isEmpty() || isMatchedEmptyOperandPattern(value)) {
        return EMPTY_ARRAY;
    }

    Matcher matcher = customPattern.matcher(value);
    if (!matcher.matches()) {
        throw new IllegalArgumentException();
    }

    String customDelimiter = this.convertEscapedString(matcher.group(INDEX_OF_DELIMITER));
    return matcher.group(INDEX_OF_VALUE).split(customDelimiter);
}

private boolean isMatchedEmptyOperandPattern(final String value) {
    return emptyOperandPattern.matcher(value)
                .matches();
}
```
- 이렇게 변경하니까 의도도 확실하게 보이고 훨씬 깔끔해진 거 같네요ㅎㅎㅎ 👍 감사합니다~

2020-05-19 08:28 UTC, nokchax commented
수정할 점!
1.  set을 사용하므로 스플리터 클래스들 equals hash 오버라이딩하기 
2. matcher.find() 다른 부분도 matcher.matches()로 수정하기
3.  pattern.match(value) 중복 코드 제거

머지 할게요 수고하셨슴다 :)

2020-05-19 08:29 UTC, merged

2020-05-29 10:54 UTC, nokchax reviewed
END