Step2 - 로또(자동)
zuniors/java-lotto pull request #2
Opened 2020-05-20 23:14 UTC by gmlwjd9405

## 기능 요구사항 목록 
### # M (Model)
#### LottoNumber
: 로또 숫자 범위 내의 숫자 
- [x] 1 ~ 45 까지의 정수 이외의 값이면 예외가 발생한다.
- [x] 로또 번호 범위 1 ~ 45 사이의 정수면 로또 숫자를 생성할 수 있다.

#### LottoTicket
: 로또 숫자에 대한 일급 컬렉션 
- [x] List<Integer> 을 받아 LottoTicket 을 생성할 수 있다.
- [x] 로또 슷자의 개수가 6개가 아니면 예외가 발생한다.
- [x] 로또 슷자가 0 ~ 45 사이의 숫자가 아니면 예외가 발생한다.
- [x] 당첨 번호와 일치하는 숫자의 개수를 구할 수 있다.
- [x] 특정 숫자가 티켓에 포함되어 있으면 true 를 반환한다.
- [x] 중복된 숫자를 가질 수 없다. 
    - Set 으로 구성함.

#### ~~LottoTickets~~
: LottoTicket 에 대한 일급 컬렉션
- [ ] 구입한 LottoTicket 을 추가할 수 있다.

#### WinningLottoTicket
: 로또 당첨 번호 
- [x] String 배열로 된 입력받은 정보로 로또 당첨번호를 생성할 수 있다.
- LottoTicket 과 동일 
    - [x] 로또 슷자의 개수가 6개가 아니면 예외가 발생한다.
    - [x] 로또 슷자가 0 ~ 45 사이의 숫자가 아니면 예외가 발생한다.
    - [x] 특정 숫자가 티켓에 포함되어 있으면 true 를 반환한다.
    
#### Prize
: 일치하는 개수에 대한 상금액 (당첨 개수별 상)
- [x] 일치하는 개수에 맞는 Prize 객체를 반환한다.

#### LottoPrizeResult (테스트 코드 어떻게?)
: 당첨 개수에 일치하는 티켓의 개수를 관리 
- [x] 결과값을 초기화하면 당첨 개수에 일치하는 티켓 개수는 모두 0으로 설정된다.
- [x] 당첨 개수에 일치하는 티켓 개수를 설정할 수 있다.
- [x] 해당하는 Prize 의 개수를 1씩 증가시킬 수 있다. 
- [x] 총 수익률을 반환한다. 
    - (최종 상금액 / 구매액)
    - (private) 최종 상금액을 반환한다. : 상금액 별 (상금액 * 당첨된 티켓 개수 = 당첨액)의 합 

#### LottoSeller
: LottoTickets 를 금액만큼 구매하는 책임 
- [x] 로또 1장의 가격(1000원)보다 낮은 금액을 내면 예외가 발생한다.
- [x] 로또 구입 금액에 맞는 로또 티켓을 반환한다.
    - (티켓의 크기로 알 수 있음) 로또 구입 금액에 따라 구입 개수를 구할 수 있다.
    - (동일) 로또 구입 개수 만큼의 로또 복권을 생성할 수 있다.

#### RandomGenerationStrategy
: 로또 숫자를 랜덤으로 생성하는 전략 
- [x] 1 ~ 45 중 6개의 숫자를 랜덤으로 생성할 수 있다.
- [x] 랜덤으로 생성한 숫자는 1 ~ 45 사이의 값이다.
- [x] 랜덤으로 생성한 숫자에 중복된 값은 없다.

#### LottoGame (테스트 코드 어떻게?)
: 구매한 티켓과 로또 당첨 번호로 로또 결과 수행 
- [x] 구매한 티켓과 로또 당첨 번호에 맞는 결과를 반환한다.

### # V (View)
#### InputView
- [x] 구입금액을 입력받을 수 있다.
- [x] 지난 주 당첨 번호를 입력받을 수 있다.

#### ResultView
- [x] 구매한 티켓의 개수를 출력할 수 있다. 
- [x] 구매한 티켓의 번호를 출력할 수 있다.
- [x] 당첨 개수에 일치하는 티켓 개수를 출력할 수 있다.
- [x] 총 수익률을 출력할 수 있다. 

### # C (Controller)
#### LottoApplication
- input: 구매 금액 입력
- business logic: 티켓 구매  
- output: 구매 개수 출력
- output: 구매한 티켓 정보 출력 
- input: 지난 주 당첨 번호 입력
- business logic: 당첨 번호에 맞게 통계를 내는 게임 수행 
- output: 통계 결과 출력

2020-05-20 23:21 UTC, gmlwjd9405 commented
마지막에 구입한 티켓과 당첨 번호에 맞는 상금 결과를 반환하는 부분을 구현할 때 기능 요구 사항에 있는 아래의 두 클래스에 대한 테스트 코드를 구현할 방법을 잘 모르겠어서 TDD를 제대로 수행하지 못했습니다... 😢 
- LottoPrizeResult (테스트 코드 어떻게?)
- LottoGame (테스트 코드 어떻게?) 

테스트 코드를 짜려고 하면 getter 메서드가 필요하거나 아니면 불필요한 반환값을 추가해야 구현할 수 있기 때문에 테스트 코드를 위한 로직 코드의 추가/변경이 일어나는 것으로 생각되어 우선 로직을 먼저 구현하게 되었습니다.

Q. 혹시 저 두 클래스에 대해 테스트 코드를 짜기 위한 기존 코드 변경이 옳은 것인지
Q. 저 두 클래스는 테스트 코드가 필요없는 클래스인지
Q. 아니면 제 구조나 설계에 문제가 있는지 
궁금합니다!

2020-05-21 04:46 UTC, nokchax requested changes
1. 테스트 코드를 위해서 기존 코드를 변경하는 건 좋지 않다고 생각해요, 배보다 배꼽이 커지지 않을까요? (단순 변수의 접근 제한자 변경은 예욉니다 ㅎ)
2. 요건 저도 고민인데, 요즘 코드짜면서 하는 생각은 내부적으로 로직이 크게 없다면(예를 들어 단순 객체 생성, getter 등) 굳이 필요할까 싶기도 하네요, 
   하지만 메소드 내부가 언제 변경될지 모르기도하고 테스트 코드가 없는 상태에서 내부로직이 변경이 됐고, 테스트가 필요하게 됐는데 테스트코드 작성을 넘길수도 있어서 위험할거 같기도 하구.. 저도 고민이에요 🤔🤔🤔🤔🤔🤔 그래서 일단 최소한으로만 테스트!

- LottoPrizeResult의 경우에는 내부적으로 복잡해서 그런것도 있는것 같네요
  - matchedPrizes를 외부에서 처리한다음 객체를 초기화 하면 테스트 할 것도 줄어들 거 같아요
  - 현재 구조에서 테스트를 한다면, 아래 정도로 충분하지 않을까요?
    1. 객체생성
    2. Prize update
    3. profit 계산 비교로 테스트
- LottoGame의 경우
  - 테스트할게 초기화와 play정도인데 초기화는 별 문제될게 없으니까 (assertThatCode() 정도?) 넘어가고
  - play의 경우에는 
    1. LottoGame 초기화
    2. play(winningLottoTicket)로 LottoPrizeResult 반환
    3. 예상되는 LottoPrizeResult 객체와 비교 (equals 메소드 오버라이딩) 정도면 될거 같아요

3. 구조적 개선이라고 해야할지 모르겠지만, 
- 전략패턴을 범용적으로 만들었다는 점
- 일급 컬렉션을 적용할 수 있는데 적용하지 않았다는 점
- 객체간의 연관관계, 객체내의 필드값에 대한 재고가 필요한 점

정도가 개선점으로 보여요.
어떤 객체를 조금 더 작게 분리하고, 어떤 객체들을 하나로 모아야 할지. 
또, 한 객체 내에서 추가해도 될 필드가 있는지 조금 더 고민해보아요.

어디까지나 개인적인 생각! 거생하셨슴돠 😁😁😁

2020-05-21 04:46 UTC, nokchax commented on README.md
> +# 1단계 - 문자열 덧셈 계산기
꼼꼼스 📝 👍

2020-05-21 04:46 UTC, nokchax commented on src/main/java/lotto/LottoApplication.java
> +        int amount = InputView.inputPurchaseAmount();
amount는 함축적인 단어 같아요. 지불금액 같은 의미의 payment는 어떨까요?

2020-05-21 04:46 UTC, nokchax commented on src/main/java/lotto/LottoApplication.java
> +        ResultView.printTickets(tickets);
`printPurchaseInfo(List<LottoTicket> tickets)` 같은 함수로 묶어서 처리해도 되지 않을까요?

2020-05-21 04:46 UTC, nokchax commented on src/main/java/lotto/domain/number/LottoNumber.java
> +            throw new InvalidParameterException("1 ~ 45 사이의 숫자가 아닙니다.");
MIN_VALUE, MAX_VALUE 상수를 사용하면 더 좋을거 같아요 :)

2020-05-21 04:46 UTC, nokchax commented on src/main/java/lotto/domain/number/LottoNumber.java
> +    private int number;
final을 붙이는게 어떨까요? 한번 생성하면 불변인 필드일거 같은데,
참고로 intellij 최신버전을 사용하면 final키워드를 붙일 수 있는 필드는 경고 표시를 띄워준답니다 ㅎㅎ

2020-05-21 04:46 UTC, nokchax commented on src/main/java/lotto/domain/prize/LottoPrizeResult.java
> +    private final EnumMap<Prize, Integer> matchedPrizes;
EnumMap 👍👍👍

2020-05-21 04:46 UTC, nokchax commented on src/main/java/lotto/domain/prize/Prize.java
> +    FIRST(6,  2000000000);
```suggestion
    FIRST(6, 2_000_000_000);
```
java7부터는 위처럼 선언해서 가독성을 높일수 있다고 해요 ㅎㅎ

2020-05-21 04:46 UTC, nokchax commented on src/main/java/lotto/domain/prize/Prize.java
> +    FIRST(6,  2000000000);
공백이 추가적으로 들어갔어요!

2020-05-21 04:46 UTC, nokchax commented on src/main/java/lotto/domain/prize/Prize.java
> +    private int prizeMoney;
여기도 final 선언이 가능하네요

2020-05-21 04:46 UTC, nokchax commented on src/main/java/lotto/domain/ticket/LottoTicket.java
> +    private static final String LOTTO_NUMBER_DELIMITER = ", ";
사소한 건데 ", " 보다 "," 로 선언하고 trim을 해주는게 어떨까요?

2020-05-21 04:46 UTC, nokchax commented on src/main/java/lotto/domain/ticket/LottoTicket.java
> +            throw new IllegalArgumentException();
메세지도 써주면 좋을거 같아요

2020-05-21 04:46 UTC, nokchax commented on src/main/java/lotto/domain/ticket/WinningLottoTicket.java
> +public class WinningLottoTicket {
WinningLottoTicket과 LottoTicket은 비슷한 점이 많지 않을까요?
다른점이 있다면 보너스 숫자를 가지고 있다는 점?

2020-05-21 04:46 UTC, nokchax commented on src/main/java/lotto/domain/strategy/NumberGenerationStrategy.java
> +public interface NumberGenerationStrategy {
`List<Integer>` 를 반환하는거는 범용적인거 같은데
로또와 관련되게 특화시키는건 어떨까요?
`List<LottoNumber>` or `LottoNumbers` 객체 리턴

2020-05-21 04:46 UTC, nokchax commented on src/main/java/lotto/domain/strategy/RandomGenerationStrategy.java
> +    private List<Integer> generateRangeNumbers(final int min, final int max) {
동일한 범위의 값을 매번 생성할 필요가 있을까요?
큰 차이는 없지만 정적 변수로 선언해두고 copy하는 식으로 사용하는건 어떨까요?

2020-05-21 04:46 UTC, nokchax commented on src/main/java/lotto/domain/ticket/LottoTicket.java
> +    private Set<LottoNumber> numbers;
`Set<LottoNumber> numbers` 를 하나의 필드로 가지고 있다 보니까 이 ticket 클래스 코드가 길어진 감이있네요
LottoNumbers라는 클래스로 추출하면 어떨거 같나요
정적 팩토리 메소드도 간결해지고, 당첨 번호 체크하는 로직만 가지게 되어서 간결해질거 같은데

2020-05-21 04:46 UTC, nokchax commented on src/main/java/lotto/domain/view/ResultView.java
> +package lotto.domain.view;
view 패키지에 있는 클래스는 domain은 아닌거 같아요
domain 패키지는 빼도 될거같은데?

2020-05-21 04:46 UTC, nokchax commented on src/main/java/lotto/domain/prize/Prize.java
> +                .orElse(Prize.MISS);
회귀했군요 😢, Map<Integer, Prize> 를 활용해보도록 해요!

2020-05-21 04:46 UTC, nokchax commented on src/main/java/lotto/domain/LottoGame.java
> +        );
```suggestion
        this.tickets.stream()
              .map(lottoTicket -> lottoTicket.matchPrize(winningLottoTicket))
              .collect(Collectors.groupingBy(Function.identity(), Collectors.counting()));
```
이런식으로 하고, LottoPrizeResult 객체를 초기화 할때 넘겨주는게 어떨까요?

2020-05-21 04:46 UTC, nokchax commented on src/main/java/lotto/domain/prize/LottoPrizeResult.java
> +                .sum();
```suggestion
                .mapToInt(this::calculatePrizes)
                .sum();
```

2020-05-21 04:46 UTC, nokchax commented on src/main/java/lotto/domain/prize/LottoPrizeResult.java
> +    }
함수로 추출해서 의미가 명확하게 전달되네요 👍

2020-05-21 04:46 UTC, nokchax commented on src/main/java/lotto/domain/seller/LottoSeller.java
> +            tickets.add(LottoTicket.of(generationStrategy.generate()));
LottoTicket.auto(); 같은 방식으로 내부에서 처리하는 방식은 어떨까요

2020-05-21 04:46 UTC, nokchax commented on src/main/java/lotto/domain/seller/LottoSeller.java
> +    public List<LottoTicket> buyTicket(final int money) {
`List<LottoTicket>` 보단 일급컬렉션 적용이 가능할거 같은데

2020-05-21 04:46 UTC, nokchax commented on src/main/java/lotto/domain/ticket/LottoTicket.java
> +                .count());
Math.toIntExact 👍

2020-05-21 04:46 UTC, nokchax commented on src/main/java/lotto/domain/LottoGame.java
> +
객체를 생성할때 구매금에 대한 정보도 같이 넣어두면, matchResult 객체를 생성할때 구매금 정보도 넘겨줄수 있고, 그렇게되면 파라미터 전달없이도 수익률을 구할수 있지 않을까요?

음 어떤 느낌이냐면 구매정보, 구매한 로또티켓 은 같이 묶여 다녀야 하는 정보라고 봐야 하나? 수익률은 구매금에 대해 구입한 로또로 구할 수있는거니까 같이 다녀야하지 않겠어요?

글로 의미 전달이 됐을지 모르겠네요

2020-05-21 04:46 UTC, nokchax commented on src/main/java/lotto/domain/prize/LottoPrizeResult.java
> +    }
toString을 오버라이딩 하는건 좋은데, console 결과를 보여주는것(뷰)에 종속적인 형식은 좋지 않을거 같아요.
지금은 콘솔 환경에서 아래와 같은 포멧으로 출력을 하죠
x개 일치 (y원) - z개

그런데 다음과 같이 웹환경에서 테이블 형식으로 결과를 보여준다고 가정해볼게요?
|일치|당첨금|개수|
|---|---|---|
|3개 일치|5000원|1개|
|4개 일치|50000원|1개|
|5개 일치|15000000원|0개|
|6개 일치|2000000000원|1개|

총 수익률은 ..%입니다

그러면 어떻게 되나요 LottoPrizeResult 객체의 toString을 사용하지 않게되고, 객 값에 대한 getter가 추가 되겠죠?
현재는 View 환경에 따라 도메인에 변경이 생기게 되는 구조인거 같아요. 그래서 이전 레이싱 게임에서도
이와 관련된 코멘트를 남겼었구요.
제 생각에는 DTO를 추가해서 필요한 정보만 추린다음에 DTO의 getter를 사용해서 결과를 그려주는게 좋아보이는데 어떻게 생각하시나요?

2020-05-21 04:46 UTC, nokchax commented on src/main/java/lotto/LottoApplication.java
> +        LottoSeller seller = LottoSeller.of(new RandomGenerationStrategy(LottoTicket.LOTTO_NUMBER_SIZE));
로또의 경우에는 자동(랜덤) 생성, 수동 생성 이외의 경우가 있을까요?
수동 생성의 경우에는 generate strategy가 필요하지 않고 넘겨주는 숫자 리스트 가지고 티켓을 만들어주면 되는데, 전략 패턴은 과한거 같지 않나요?

차라리 LottoNumberGenerator이라는 객체를 만들고 해당객체는 LottoNumber 6개를 리턴해주는 식으로 해서
LottoSeller 객체 내에서만 사용하는게 나을거 같아요

2020-05-21 04:46 UTC, nokchax commented on src/test/java/lotto/domain/number/LottoNumberTest.java
> +    @ValueSource(ints = { -1, 0, 46, 1000 })
```suggestion
    @ValueSource(ints = { -1, MIN_VALUE - 1, MAX_VALUE + 1, 1000 })
```
이런 것도 괜찮을거 같아요

2020-05-21 04:46 UTC, nokchax commented on src/test/java/lotto/domain/number/LottoNumberTest.java
> +public class LottoNumberTest {
equals 에 대한 테스트도 추가하도록해요!

2020-05-21 04:46 UTC, nokchax commented on src/test/java/lotto/domain/strategy/RandomGenerationStrategyTest.java
> +        randomNumbers = new RandomGenerationStrategy(6).generate();
```suggestion
        randomNumbers = new RandomGenerationStrategy(LOTTO_NUMBER_SIZE).generate();
```

2020-05-21 04:46 UTC, nokchax commented on src/test/java/lotto/domain/seller/LottoSellerTest.java
> +                .isEqualTo(money / 1000);
```suggestion
                .isEqualTo(money / ONE_TICKET_PRICE);
```

2020-05-21 04:46 UTC, nokchax commented on src/main/java/lotto/domain/seller/LottoSeller.java
> +        this.generationStrategy = generationStrategy;
null check!

2020-05-21 04:46 UTC, nokchax commented on src/test/java/lotto/domain/ticket/LottoTicketTest.java
> +    }
요거는 개인적인 생각이 궁금한데,
이런 경우는 이미 LottoNumberTest에서 테스트 했다고 생각해서, 중복인거 같은데
어떻게 생각해요? 내부에서 테스트 했어도, 또 해줘야 한다?

2020-05-21 06:05 UTC, gmlwjd9405 commented on src/test/java/lotto/domain/ticket/LottoTicketTest.java
> +    }
넵! 클래스의 구조가 어떤식으로든 바뀌었을 때 어쨌든 해당 로직은 LottoTicket 에 있는 로직이기 때문에 한번 더 확인해주는 것이 좋을 것이라고 생각했습니다~ㅎㅎㅎ

2020-05-22 12:11 UTC, gmlwjd9405 commented
궁금한 것이 있습니다! 패키지 구조를 어떻게 짜는 것이 좋을지...
Price 라는 클래스가 이번에 추가되었는데, domain 내부에 적절한 패키지가 없어서 그냥 domain 바로 하위에 뒀는데, 조언 부탁 드립니다~ 😄

2020-05-22 17:46 UTC, nokchax approved these changes
수정하느라 수고헀어요! 👏👏👏
테스트 코드도 꼼꼼히 짰고, 개선했으면 했던 사항들도 잘 반영했구,
도메인으로 부터 뷰에 관련된 코드를 잘 분리해내셨습니다!
이제 구조적으로 문제 없어 보입니다 👍 
추가적으로 코드를 다듬을 수 있는 부분에 대해서 코멘트 남겼어요!
일단 머지하도록 할게요! 😄😄😄 

아 그리고 Price 클래스는 그냥 price 혹은 money라는 패키지에 추가하면 될거 같은데요?
패키지에 하나의 클래스만 있는게 신경쓰여서 그러시는건가요?
제 생각에는 패키지 추가 구성하는데는 크게 고민 안하셔도 될 거 같아요. 네이밍만 잘 하면 될 거 같습니다!

2020-05-22 17:46 UTC, nokchax commented on src/main/java/lotto/LottoApplication.java
> +        LottoSeller seller = LottoSeller.of();
팩토리 메서드 패턴에서 무항의 경우에는 of가 안어울리는거 같아요 😅

2020-05-22 17:46 UTC, nokchax commented on src/main/java/lotto/domain/dto/LottoTicketDto.java
> +public class LottoTicketDto {
👍

2020-05-22 17:46 UTC, nokchax commented on src/main/java/lotto/domain/dto/LottoTicketDto.java
> +    }
LottoTickets 에서도 DTO 에 대한 코드가 없도록 잘 구현하셨습니다 😃 👏👏👏

2020-05-22 17:46 UTC, nokchax commented on src/main/java/lotto/domain/number/LottoNumbers.java
> +    public List<Integer> getNumbersToInts() {
```suggestion
    public List<Integer> getNumbersAsInt() {
```
요게 좀 더 어울리는 표현같아요

2020-05-22 17:46 UTC, nokchax commented on src/main/java/lotto/domain/number/LottoNumbersGenerator.java
> +                    .collect(Collectors.toList());
여기서 조금만 더 나가면
```suggestion
    private static final List<LottoNumber> LOTTO_NUMBERS_POOL =
            IntStream.rangeClosed(LottoNumber.MIN_VALUE, LottoNumber.MAX_VALUE)
                    .boxed()
                    .map(LottoNumber::of)
                    .collect(Collectors.toList());
```
캐시해서 재사용 할 수 있고, 아래쪽에서 converToLottoNumbers 함수도 없앨수 있겠어요!

2020-05-22 17:46 UTC, nokchax commented on src/main/java/lotto/domain/prize/LottoPrizeResult.java
> +        return ((float) this.calculateTotalPrizes() / price.getPrice());
Price 클래스에도 써놨지만
상금도 금액이니까 Price 객체를 사용하면 Price 로 이 로직을 옮길 수 있겠네요

2020-05-22 17:46 UTC, nokchax commented on src/main/java/lotto/domain/prize/Prize.java
> +        return PRIZES.get(matchedNumbersCount);
```suggestion
        return PRIZES.getOrDefault(matchedNumbersCount, MISS);
```
😲띠용?

2020-05-22 17:46 UTC, nokchax commented on src/main/java/lotto/domain/prize/Prize.java
> +            .collect(Collectors.toMap(Prize::getMatchedNumbersCount, Function.identity()));
👍👍👍

2020-05-22 17:46 UTC, nokchax commented on src/main/java/lotto/domain/seller/LottoSeller.java
> +        return LottoTickets.of(tickets);
```java
        List<LottoTicket> tickets = Stream.generate(LottoNumbers::auto)
                .limit(price.ticketCount())
                .map(LottoTicket::of)
                .collect(Collectors.toList());

        return LottoTickets.of(tickets);
```
ㅎㅎ 배운거 써먹기 🤓

2020-05-22 17:46 UTC, nokchax commented on src/main/java/lotto/domain/ticket/LottoTicket.java
> +        int matchCount = lottoNumbers.matchCount(winningLottoTicket);
```java
private final LottoNumbers lottoNumbers;
````
를
```java
protected final LottoNumbers lottoNumbers;
````
로 변경하면 아래처럼 필드에 직접 접근이 가능하고, 그러면 contains 함수를 없앨 수 있어요!
물론 LottoNumbers도 수정이 조금 필요하지만요ㅎ
```suggestion
        int matchCount = lottoNumbers.matchCount(winningLottoTicket.lottoNumbers);
```

2020-05-22 17:46 UTC, nokchax commented on src/main/java/lotto/domain/ticket/LottoTickets.java
> +    }
👍

2020-05-22 17:46 UTC, nokchax commented on src/main/java/lotto/domain/ticket/WinningLottoTicket.java
> +        return new WinningLottoTicket(LottoNumbers.of(winningNumbers)); // null 인 경우?
winningNumber가 null인 경우엔 LottoNumbers.of() 메소드 내부에서 NPE가 일어나겠네요!
LottoNumbers.of() 메소드에서 검증 로직이 추가 되어야해요

2020-05-22 17:46 UTC, nokchax commented on src/main/java/lotto/domain/ticket/WinningLottoTicket.java
>      }
이 코드는 어차피 부모 클래스의 contains를 호출하니까 삭제해도 돼요!
그리고, LottoNumbers를 protected로 변경하면 contains 함수도 삭제할 수 있으니까
이러나 저러나 삭제해야겠네요

2020-05-22 17:46 UTC, nokchax commented on src/main/java/lotto/exception/ErrorMessage.java
> +public class ErrorMessage {
👍 대신 private 기본 생성자 추가할 것!

2020-05-22 17:46 UTC, nokchax commented on src/main/java/lotto/view/ResultView.java
> +        System.out.println(stringBuilder);
👍 그런데 builder를 사용할 필요가 있을까요?
코드가 더 복잡한 느낌인데, sout해도 될 거 같아요

2020-05-22 17:46 UTC, nokchax commented on src/test/java/lotto/domain/LottoGameTest.java
> +        tickets.add(LottoTicket.of(LottoNumbers.of("1, 2, 3, 4, 5, 6")));
요런 경우는 테스트를 위해서, 테스트 패키지 내부에 Generator 유틸 클래스를 만드는 것도 괜찮을거 같아요
아래는 제가 사용했던 코드!

```java
public class Generator {

    private Generator() {}

    public static List<LottoNumber> lottoNumberList(final int... numbers) {
        return Arrays.stream(numbers)
                .mapToObj(LottoNumber::of)
                .collect(Collectors.toList());
    }

    public static LottoNumbers lottoNumbers(final int... numbers) {
        return LottoNumbers.init(lottoNumberList(numbers));
    }

    public static LottoTicket lottoTicket(final int... numbers) {
        return LottoTicket.init(lottoNumbers(numbers));
    }

    public static WinningNumbers winningLotto(final int... numbers) {
        return WinningNumbers.init(lottoNumbers(numbers));
    }

    public static LottoTickets lottoTickets(final LottoTicket... lottoTickets) {
        return LottoTickets.init(Arrays.asList(lottoTickets));
    }
}
```

2020-05-22 17:46 UTC, nokchax commented on src/test/java/lotto/domain/LottoGameTest.java
> +    }
👍

2020-05-22 17:46 UTC, nokchax commented on src/main/java/lotto/domain/Price.java
> +public class Price {
Price 보다는 Money가 낫지 않을까요?
Money라는 객체 내에서 가격이라는 걸 표현하기 좀 그러면 Money를 상속해서 Price라고 사용할 수 도 있구요
로또 상금에 대한 것도 표현 가능해 지구요
구입 금액과 상금을 Money라는 객체를 이용해서 수익률을 구할 수 도 있겠네요

2020-05-22 17:46 UTC, nokchax commented on src/main/java/lotto/domain/LottoGame.java
> +    private LottoGame(final Price price, final LottoTickets tickets) {
null 체크가 필요할거 같아요

2020-05-22 17:46 UTC, nokchax commented on src/main/java/lotto/domain/number/LottoNumbers.java
> +    }
```suggestion
    public int matchCount(final LottoNumbers winningLottoNumbers) {
        return Math.toIntExact(numbers.stream()
                .filter(winningLottoNumbers::contains)
                .count());
    }
```
요로면 LottoTicket이랑 WinningLottoTicket에 존재하는 contains 함수 제거 가능!

2020-05-22 17:56 UTC, nokchax commented on src/main/java/lotto/domain/prize/LottoPrizeResult.java
> +                    matchedPrizes.put(prize, prizes.get(prize).intValue());
```suggestion
                    matchedPrizes.put(prize, prizes.getOrDefault(prize, DEFAULT_MATCHED_COUNT));
```
깜빡해서 추가!

2020-05-22 17:59 UTC, nokchax commented on src/main/java/lotto/domain/prize/Prize.java
> +        return PRIZES.get(matchedNumbersCount);
리뷰하고 제 코드 보니까 저도 이렇게 해뒀네요... 역시 훈수둘 때 더 잘보여.. 😒

2020-05-22 22:43 UTC, gmlwjd9405 commented on src/main/java/lotto/LottoApplication.java
> +        LottoSeller seller = LottoSeller.of();
무항: newInstance
하나의 항: of
여러개의 항: valueOf

까먹지 말아야겠어요...! 😖

2020-05-22 22:47 UTC, gmlwjd9405 commented on src/main/java/lotto/domain/number/LottoNumbersGenerator.java
> +                    .collect(Collectors.toList());
오호 그렇네요!!ㅎㅎㅎ 👍

2020-05-22 23:14 UTC, gmlwjd9405 commented on src/main/java/lotto/domain/seller/LottoSeller.java
> +        return LottoTickets.of(tickets);
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 굳~~ 👍

2020-05-22 23:17 UTC, gmlwjd9405 commented on src/main/java/lotto/domain/ticket/WinningLottoTicket.java
> +        return new WinningLottoTicket(LottoNumbers.of(winningNumbers)); // null 인 경우?
ㅎㅎ.. 주석으로 적어놓고 구현하질 않았네요.. 😭

2020-05-22 23:34 UTC, gmlwjd9405 commented on src/main/java/lotto/domain/number/LottoNumbers.java
> +    }
상속을 이용!

`protected final LottoNumbers lottoNumbers;` 로 접근 지정자를 변경하면 
자식 클래스에서는 필드에 직접 접근이 가능
LottoNumbers의 contains 로 matchCount 를 구할 수 있다. (LottoTicket, WinningLottoTicket의 contains 제거 가능)

[관련 리뷰 1](https://github.com/zuniors/java-lotto/pull/2#discussion_r429363335)
[관련 리뷰 2](https://github.com/zuniors/java-lotto/pull/2#discussion_r429365279)

훨씬 더 깔끔해지네요~ 👍

2020-05-22 23:39 UTC, gmlwjd9405 commented on src/test/java/lotto/domain/LottoGameTest.java
> +        tickets.add(LottoTicket.of(LottoNumbers.of("1, 2, 3, 4, 5, 6")));
오오!! 이런 방법도 있군요.
테스트 코드 예시 작성하기가 훨씬 수월할 거 같아요~ 적용해보겠습니다ㅎㅎ 👍 😄 👍

2020-05-23 03:47 UTC, nokchax commented on src/main/java/lotto/domain/number/LottoNumber.java
> +public class LottoNumber implements Comparable<LottoNumber> {
good!

2020-05-23 03:48 UTC, merged