Step4 - 로또(수동)
zuniors/java-lotto pull request #5
Opened 2020-05-26 14:55 UTC by gmlwjd9405

## 기능 요구사항 목록 
### # M (Model)
#### Price
: 금액과 관련된 클래스
- [x] 구매 가능한 개수인지 확인할 수 있다. 

#### LottoNumber
: 로또 숫자 범위 내의 숫자 

#### LottoNumbers
: 로또 숫자에 대한 일급 컬렉션 

#### LottoTicket
: LottoNumbers 에 대한 Wrapping 클래스 

#### LottoTickets
: LottoTicket 에 대한 일급 컬렉션
- [x] LottoTicket 의 개수는 반환할 수 있다.
- [x] 인자로 입력받은 LottoTickets를 이어 붙인 LottoTickets를 반환할 수 있다.

#### WinningLottoTicket
: 로또 당첨 번호 
    
#### Prize
: 일치하는 개수에 대한 상금액 (당첨 개수별 상)

#### LottoPrizeResult
: 당첨 개수에 일치하는 티켓의 개수를 관리 

#### LottoSeller
: LottoTickets 를 금액만큼 구매하는 책임 
- [x] 수동으로 입력한 로또 티켓이 구매할 수 있는 티켓의 수보다 많으면 예외 반환
- [x] 수동으로 입력한 로또 티켓 수를 구매하고 남은 돈으로 자동으로 로또 티켓을 생성한다.

#### LottoNumberGenerator
: 로또 숫자를 랜덤으로 자동 생성하는 책임 

#### LottoGame (테스트 코드 어떻게?)
: 구매한 티켓과 로또 당첨 번호로 로또 결과 수행 

#### LottoTicketDTO
: 화면 출력에 필요한 정보에 대한 DTO

### # V (View)
#### InputView
- [x] 수동으로 구매할 로또 수를 입력받는다.
- [x] 수동으로 구매할 로또 수 만큼 로또 번호를 입력받는다.

#### ResultView
- [x] 수동, 자동으로 구매한 개수를 출력한다. 

### # C (Controller)
#### LottoApplication
- input: 구매 금액 입력
- business logic: 티켓 구매  
- output: 구매 개수 출력
- output: 구매한 티켓 정보 출력 
- input: 지난 주 당첨 번호 입력
- business logic: 당첨 번호에 맞게 통계를 내는 게임 수행 
- output: 통계 결과 출력

2020-05-26 15:35 UTC, nokchax requested changes
수고하셨슴돠 👍
구조가 깔끔해서 변경할게 많지 않았네요, 자잘한 코멘트 약간 달아봤습니다!

2020-05-26 15:35 UTC, nokchax commented on src/main/java/lotto/view/InputView.java
> +        }
```suggestion
        List<LottoNumbers> lottoNumbers = 
        Stream.generate(() -> convertToLottoNumbers(SCANNER.nextLine()))
                .limit(manualTicketsCount)
                .map(LottoNumbers::manualCreate)
                .collect(Collectors.toList()
```
스트림 적용가능해요😄

2020-05-26 15:35 UTC, nokchax commented on src/main/java/lotto/view/InputView.java
> +                        .limit(manualTicketsCount)
```suggestion
```
litmit은 필요없지 않을까요?

2020-05-26 15:35 UTC, nokchax commented on src/main/java/lotto/domain/ticket/LottoTickets.java
> +        mergeTickets.addAll(tickets.getLottoTickets());
```suggestion
        mergeTickets.addAll(tickets.lottoTickets);
```
리마인드 차원에서! 요거 잊지 않으셨죠? ㅎㅎ

2020-05-26 15:35 UTC, nokchax commented on src/main/java/lotto/domain/ticket/LottoTickets.java
> +        List<LottoTicket> mergeTickets = new ArrayList<>(lottoTickets);
merge는 동사형이니까 merged 정도가 나을거 같아요

2020-05-26 15:35 UTC, nokchax commented on src/main/java/lotto/domain/seller/LottoSeller.java
> +    public LottoTickets buyTicket(final Price price, final LottoTickets manualTickets) {
LottoSeller는 필드도 없어서, 객체를 생성할 필요 없이 static으로 만들수 있을거 같은데?? 어때요??

2020-05-26 15:35 UTC, nokchax commented on src/main/java/lotto/view/ResultView.java
> +    public static void printPurchaseInfo(final int manualTicketsCount, final List<LottoTicketDto> tickets) {
흐음... 여기는 좀 생각해봤으면 해서 적어봅니다.
구입한 로또에 대해서 출력하는데, 현재 구조는 정보가 점점 더 많아지게 되면 그만큼 필요한 인자수가 늘어날 거 같아요, 파라미터로 전달하는 수가 적으면 적을수록 좋기 때문에. 구입 정보에 대한 클래스를 만들고 그쪽으로 구입한 정보를 합쳐보는건 어떨까요?

만약 하나로 합치게되면, 수동 티켓 수도 그 클래스 내부에서 구할수 있을거구요

2020-05-27 01:54 UTC, gmlwjd9405 commented on src/main/java/lotto/view/InputView.java
> +                        .limit(manualTicketsCount)
이미 앞에서 읽어올 때 입력한 개수만 읽기 때문에 한번 더 체크한다는 의미긴 했는데, 
필요 없을 것  같네요 :)

2020-05-27 01:54 UTC, gmlwjd9405 commented on src/main/java/lotto/view/InputView.java
> +        }
step3 피드백 받기 전이라 다시 수정을 안해뒀네요...ㅎㅎ
적용하겠습니다. 👍

2020-05-27 01:56 UTC, gmlwjd9405 commented on src/main/java/lotto/domain/seller/LottoSeller.java
> +    public LottoTickets buyTicket(final Price price, final LottoTickets manualTickets) {
그럼 나중에라도 LottoSeller와 관련된 필드가 생기면 그때 다시 static 을 제거하는 것이 좋을까요?

2020-05-27 01:58 UTC, gmlwjd9405 commented on src/main/java/lotto/view/ResultView.java
> +    public static void printPurchaseInfo(final int manualTicketsCount, final List<LottoTicketDto> tickets) {
변경해보도록 하겠습니다!

2020-05-27 02:00 UTC, nokchax commented on src/main/java/lotto/domain/seller/LottoSeller.java
> +    public LottoTickets buyTicket(final Price price, final LottoTickets manualTickets) {
네! 필드가 없다면 그게 나아보여요ㅎㅎ

2020-05-27 10:36 UTC, gmlwjd9405 commented on src/main/java/lotto/view/ResultView.java
> +    public static void printPurchaseInfo(final int manualTicketsCount, final List<LottoTicketDto> tickets) {
구입 정보에 대한 책임을 분리하여 수동 티켓 수, 자동 티켓 수 등에 대한 정보를 모으긴 했는데, 
출력 메서드의 인자 개수는 줄이기가 쉽지 않네요.. 조금 더 고민해보겠습니다! 😢

2020-05-29 01:37 UTC, nokchax approved these changes
수고하셨습니다 👏👏👏👏  
클래스를 잘 나누셨고, 객체들을 잘 모아서 훨씬 보기 좋아졌습니다 👍 
몇가지 개선점을 써두긴 했는데, 이미 충분해서 머지해둘게요! ✔️

2020-05-29 01:37 UTC, nokchax commented on src/main/java/lotto/LottoApplication.java
> +        PurchaseInfo purchaseInfo = LottoSeller.buyTicket(payInfo);
여러 초기화 정보들을 묶어둬서 메소드로 넘기는 파라미터도 간결해지고,
클래스명도 잘 네이민해서 훨씬 읽기 편해졌습니다. 💯

2020-05-29 01:37 UTC, nokchax commented on src/main/java/lotto/LottoApplication.java
> +        List<List<LottoNumber>> manualTicketNumbers = InputView.inputManualTickets(manualTicketsCount);
InputView에서의 역할은 List<List<Integer>> 처럼 되도록 원시값으로 리턴하는 것으로 끝내는게 좋다고 생각하는데, 어떻게 생각하시나요?
제 상각은 원시값으로 받아두고, PayInfo 클래스 내부에서 List<List<LottoNumber>> 나 List<LottoNumbers>로 변환 시켜주는게 좀 더 유연한 구조가 될거 같아요 🤔

2020-05-29 01:37 UTC, nokchax commented on src/main/java/lotto/LottoApplication.java
> +        LottoPrizeResult result = LottoGame.of(price, purchaseInfo.getAllTickets())
price와 tickets를 넘기지말고, PurchaseInfo 에서 PayInfo를 가지고 있으면, purchaseInfo 객체만 넘겨서 처리할 수 있지 않을까요?
현실세계에서도 물건을 구매하고 영수증 같은 구매 정보를 같이 받을 수 있으니까, 같이 묶어도 이상할건 없어보이는데, 그리고 전에도 말씀드렸듯이 지불 정보와 구매 정보는 같이 다녀야지 이후 계산들이 편해질거 같아요.

2020-05-29 01:37 UTC, nokchax commented on src/main/java/lotto/domain/ticket/WinningLottoTicket.java
> +        verifyDuplication(lottoNumbers, bonusLottoNumber);
중복 체크는 생성자에서 하는게 좋아보입니다

2020-05-29 01:37 UTC, nokchax commented on src/main/java/lotto/view/ResultView.java
> +    private static void printPurchasedTicketCount2(final PurchaseInfo purchaseInfo) {
요거 TDD진행하다 변경하는거 깜빡하신거 같네요 😅

2020-05-29 01:37 UTC, nokchax commented on src/main/java/lotto/domain/seller/LottoSeller.java
> +    }
👍

2020-05-29 01:37 UTC, merged

2020-05-29 01:40 UTC, gmlwjd9405 commented on src/main/java/lotto/view/ResultView.java
> +    private static void printPurchasedTicketCount2(final PurchaseInfo purchaseInfo) {
ㅎ.... 그러네여.......